services:
  loki:
    image: grafana/loki:3.3.0
#    build:
#      context: .
#      dockerfile: loki-config/Dockerfile
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config/config.yaml:/etc/loki/config.yaml
      - ./data/loki:/loki  # 데이터 저장소
    networks:
      - loki-network

  grafana:
    image: grafana/grafana:8.5.0
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin  # Grafana 기본 사용자
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Grafana 기본 비밀번호
      - TZ=${TZ}
    volumes:
      - ./data/grafana:/var/lib/grafana  # Grafana 데이터 저장
    networks:
      - loki-network
    depends_on:
      - loki

networks:
  loki-network:
    external: true