auth_enabled: false

server:
  http_listen_port: 3100

common:
#  ring: # 클러스터 구성 시 사용
#    instance_addr: 0.0.0.0
#    kvstore:
#      store: inmemory
  replication_factor: 1

compactor:
  working_directory: /loki/retention
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 50
  delete_request_store: filesystem

limits_config:
  max_query_lookback: 336h
  retention_period: 336h

schema_config:
  configs:
    - from: "2024-12-20"
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

ingester:
  wal:
    enabled: true
    replay_memory_ceiling: 4GB
  lifecycler:
    ring:
      kvstore:
        store: inmemory
