auth_enabled: false

server:
  http_listen_port: 3100
  log_level: debug

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory # Loki가 단일 인스턴스로 실행 중이며, 클러스터 모드가 아닌 단일 노드 모드로 작동
      replication_factor: 1 # 로그 데이터를 여러 노드에 복제하여 가용성과 데이터 안정성을 확보
  chunk_idle_period: 3m
  chunk_retain_period: 1m

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb
      object_store: filesystem # 로그 데이터를 파일 시스템(filesystem)에 저장
      schema: v11
      index:
        prefix: index_
        period: 24h # index.period: 24h 설정으로 인덱스가 매일 자정(UTC 기준) 새롭게 시작

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/cache
    shared_store: filesystem
  filesystem:
    directory: /loki/chunks

limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 24h
  max_look_back_period: 24h



