services:
  app1:
    build:
      context: .
      dockerfile: promtail-config/Dockerfile
    platform: linux/arm64  # Macbook에서 실행 시
    container_name: app1
    volumes:
      - ./data/app1:/data/log  # 로그 경로
      - ./promtail-config/promtail1-config.yaml:/etc/promtail/promtail-config.yaml  # Promtail 설정 파일 마운트
      - ./data/app1/promtail:/var/lib/promtail  # 위치 파일 저장 경로
    environment:
      - PROMTAIL_CONFIG=/etc/promtail/promtail-config.yaml  # app1의 Promtail 설정 파일 지정
      - TZ=Asia/Seoul
    ports:
      - "8081:8080"
    networks:
      - loki-network

  app2:
    build:
      context: .
      dockerfile: promtail-config/Dockerfile
    platform: linux/arm64  # Macbook에서 실행 시
    container_name: app2
    volumes:
      - ./data/app2:/data/log  # 로그 경로
      - ./promtail-config/promtail2-config.yaml:/etc/promtail/promtail-config.yaml  # Promtail 설정 파일 마운트
      - ./data/app2/promtail:/var/lib/promtail  # 위치 파일 저장 경로
    environment:
      - PROMTAIL_CONFIG=/etc/promtail/promtail-config.yaml  # app2의 Promtail 설정 파일 지정
      - TZ=Asia/Seoul
    ports:
      - "8082:8080"
    networks:
      - loki-network

networks:
  loki-network:
    external: true